<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);
return array(
    'Sainsburys\\Guzzle\\Oauth2\\' => array($vendorDir . '/sainsburys/guzzle-oauth2-plugin/src'),
    'QBNK\\Tests\\' => array($vendorDir . '/qbnk/guzzle5-oauth2-subscriber/tests'),
    'QBNK\\QBank\\API\\' => array($vendorDir . '/qbnk/qbank3api-phpwrapper'),
    'QBNK\\GuzzleOAuth2\\' => array($vendorDir . '/qbnk/guzzle5-oauth2-subscriber/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
);
