services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\Qbank\:
    resource: '../Classes/*'

  Pixelant\Qbank\Controller\SelectorController:
    public: true

  Pixelant\Qbank\Service\Event\FileReferenceUrlEventHandler\ContentElementFileReferenceUrlEventHandler:
    tags:
      - name: event.listener
        identifier: contentElementLocationUrl
        event: Pixelant\Qbank\Service\Event\FileReferenceUrlEvent

  Pixelant\Qbank\Service\Event\FileReferenceUrlEventHandler\PageFileReferenceUrlEventHandler:
    tags:
      - name: event.listener
        identifier: pageLocationUrl
        event: Pixelant\Qbank\Service\Event\FileReferenceUrlEvent

  Pixelant\Qbank\Service\Event\ResolvePageTitleEventHandler\FileReferenceResolvePageTitleEventHandler:
    tags:
      - name: event.listener
        identifier: fileReferencePageTitle
        event: Pixelant\Qbank\Service\Event\ResolvePageTitleEvent
        before: defaultPageTitle

  Pixelant\Qbank\Service\Event\ResolvePageTitleEventHandler\DefaultResolvePageTitleEventHandler:
    tags:
      - name: event.listener
        identifier: defaultPageTitle
        event: Pixelant\Qbank\Service\Event\ResolvePageTitleEvent

  Pixelant\Qbank\Service\Event\FilePropertyChangeEventHandler\MetaDataFilePropertyChangeEventHandler:
    tags:
      - name: event.listener
        identifier: metaDataPropertyChangeHandler
        event: Pixelant\Qbank\Service\Event\FilePropertyChangeEvent

  Pixelant\Qbank\Service\Event\CollectMediaPropertiesEventHandler\BaseMediaPropertiesCollector:
    tags:
      - name: event.listener
        identifier: baseMediaPropertiesCollector
        event: Pixelant\Qbank\Service\Event\CollectMediaPropertiesEvent

  Pixelant\Qbank\Service\Event\CollectMediaPropertiesEventHandler\PropertyMediaPropertiesCollector:
    tags:
      - name: event.listener
        identifier: propertyMediaPropertiesCollector
        event: Pixelant\Qbank\Service\Event\CollectMediaPropertiesEvent

  Pixelant\Qbank\Service\Event\ExtractMediaPropertyValuesEventHandler\BaseMediaPropertyValuesExtractor:
    tags:
      - name: event.listener
        identifier: baseMediaPropertyValuesExtractor
        event: Pixelant\Qbank\Service\Event\ExtractMediaPropertyValuesEvent

  Pixelant\Qbank\Service\Event\ExtractMediaPropertyValuesEventHandler\PropertyMediaPropertyValuesExtractor:
    tags:
      - name: event.listener
        identifier: propertyMediaPropertyValuesExtractor
        event: Pixelant\Qbank\Service\Event\ExtractMediaPropertyValuesEvent

  Pixelant\Qbank\Service\Event\AfterFilePropertyChangesEventHandler\PersistMetaDataChanges:
    tags:
      - name: event.listener
        identifier: persistMetaDataChanges
        event: Pixelant\Qbank\Service\Event\AfterFilePropertyChangesEvent
