---
name: CI
on: [push, pull_request]
jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
      - name: "Run PHP lint"
        run: "composer ci:php:lint"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2
  typoscript-lint:
    name: "TypoScript linter"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run TypoScript lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-Typoscript-Lint@v1
  yaml-lint:
    name: "YAML linter"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run YAML lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-YAML-Lint@v1
  copypaste-detector:
    name: "Copy'n'paste detector"
    runs-on: ubuntu-20.04
    needs: php-lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run the Copy'n'paste Detector"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-Copy-Paste-Detector@v1
  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install Composer dependencies"
        run: "composer install --no-progress"
      - name: "Run command"
        run: "composer ci:${{ matrix.command }}"
    strategy:
      fail-fast: false
      matrix:
        command:
          - "composer:normalize"
          - "json:lint"
          - "php:cs-fixer"
          - "php:sniff"
        php-version:
          - 8.1
          - 8.2
  xliff-lint:
    name: "Xliff linter"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run the xliff lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-Xliff-Lint@v1
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-20.04
    needs: php-lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - env:
          TYPO3: "${{ matrix.typo3-version }}"
        name: "Install TYPO3 Core"
        run: |
          composer require --no-progress typo3/minimal:"$TYPO3"
          composer show
      - if: matrix.composer-dependencies == 'lowest'
        name: "Install lowest dependencies with composer"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies --prefer-lowest
          composer show
      - if: matrix.composer-dependencies == 'highest'
        name: "Install highest dependencies with composer"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies
          composer show
      - name: "Run unit tests"
        run: "composer ci:tests:unit"
    strategy:
      fail-fast: false
      matrix:
        composer-dependencies:
          - highest
          - lowest
        php-version:
          - 8.1
          - 8.2
        typo3-version:
          - ^12.4
